### ISSUE TITLE
Feature request: Free code camp resource lookup

### ISSUE THREAD

**Issue by cronix1000** [Paulmski/Discord-Bot#11]
Possibly have a feature that has the user say a topic for example sql then it goes through the free code camp tutorials and gives back a video for that topic or if not free code camp just a top rated youtube video

**Comment by Paulmski** [comment]
Another super solid idea! Could be a very useful resource especially if we make it connect to other resources not just free code camp.

**Comment by Paulmski** [comment]
@cronix1000 Can this issue be closed or are you adding other functionality?

**Comment by Paulmski** [comment]
Closing this issue for now, please open a new issue if you would like to further develop on this feature.
