### ISSUE TITLE
Feature request: Using .env versus secrets.py

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#19]
Currently coding the Google Sheets API into the bot, and I was wondering if we could all agree to store tokens and sensitive information in a file called `.env` instead of `secrets.py`.

All we would need to do is rewrite the code to use the [`python_dotenv` library](https://pypi.org/project/python-dotenv/), drop the import to secrets, and have the .env file in the same directory as `__main__.py`. We would also have to rewrite the CONTRIBUTING and README to reflect these changes.

The degree of encryption that .env files have over `secrets.py` seems negligible (.env's are stored as plaintext anyway), but [doing so would hide it from HTTP requests](https://stackoverflow.com/questions/64314703/how-to-secure-sensitive-informations-in-settings-py#:~:text=.ENV%20files%20is%20a%20best%20practice%20in%20keeping%20sensitive%20informations).

.env files are already considered by our `.gitignore` so sensitive information cannot be automatically committed, just as it does for `secrets.py`.

**Comment by Paulmski** [comment]
Seems reasonable, security-wise as you said they seem to be very similar, but I see how it might prevent people from accidentally pushing their secret tokens to the repo.
