### ISSUE TITLE
Feature request: Embeds for announcements

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#25]
With the scheduled @everyone announcement to be sent out everyday at 6AM, the text the bot outputs can cause clutter overtime.

We should take advantage of [discord.py embeds](https://discordpy.readthedocs.io/en/stable/api.html#embed) and reformat the current `announce_due_dates()` output to look more elegant, using a [demonstration in this Medium article as reference](https://python.plainenglish.io/send-an-embed-with-a-discord-bot-in-python-61d34c711046).

**Comment by Paulmski** [comment]
I agree, it would make it look a lot more clean
