### ISSUE TITLE
Bug Report: Adding new members to study group unsuccessful despite correct argument

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#50]
When deleting a private study group, the Bot will not allow it to be deleted because the voice-channel name and text-channel name can differ if the group was created with a spaced name, ex `"My Study Group"`.

1. Create a study group using `!group create "example group"`
2. Two private channels are created: the "example-group" text channel and the "example group" voice channel.
3. Attempt to add a new user using `!group add example-group @username`
4. Bot responds that the group name in argument was not valid.

![image](https://user-images.githubusercontent.com/93796037/147968146-8111c6a1-d5d0-4e28-9dd1-b29cf733c8b7.png)

This can easily be fixed by ensuring that on creation, the group name is standardized to a certain format, such as `one-two-three-group-name` since text channel names cannot have spaces.

I am currently working on this bug and it should be easily fixed by ensuring spaces in names are replaced with dashes upon study group creation.

**Comment by Paulmski** [comment]
Oh thanks, I didn't take that into account
