### ISSUE TITLE
Bug: Repeating headers for !list

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#62]
## Describe the bug...
When calling `!list` for one of our classes, the Bot repeats the header of the first class twice.

## To Reproduce...
Detail the steps to reproduce the behavior:
1. Call `!list all`
2. Note the unexpected behavior.
![image](https://user-images.githubusercontent.com/93796037/148982627-6761a918-338d-4e4d-a311-0f9f0335f9d9.png)

3. Call `!list COMP1006`
4. Note the unexpected behavior,
![image](https://user-images.githubusercontent.com/93796037/148982894-ea55719a-c238-441c-88e5-64f6869d7cd9.png)

## Expected Behavior
The heading should only show up once for every class.
![image](https://user-images.githubusercontent.com/93796037/148983095-acb21d5b-c593-4ed7-a9e6-7b97736ddb1d.png)

**Comment by tuanyvan** [comment]
I have deduced the probable cause to be the flow logic in `events.py`, not the formatting of the Google Sheets.

**Comment by Paulmski** [comment]
@tuanyvan This is fixed?

**Comment by Paulmski** [comment]
Thanks for spotting and fixing this
