### ISSUE TITLE
Feature Request: Migration over to Pycord

### ISSUE THREAD

**Issue by tuanyvan** [Paulmski/Discord-Bot#72]
## What is the feature you would like to request?
With the `discord.py` library abandoned , it would be ideal to move the codebase over to a library with support and maintenance. In the future, changes such as Slash Commands and inability to read messages without approved intent will cause Bots using the library to stop working.

As a proactive step in keeping this project functional, migration over to another Python Discord library is required. Luckily there is a fork of the old library called [Pycord](https://github.com/Pycord-Development/pycord). It is actively maintained and supports new API features which I and other contributors have had to implement manually. These features include "slash commands, context menus, scheduled events, timeouts, and others."

EDIT: This migration to Pycord should utilize its ~~alpha version~~ recently released beta-version if we want to have access to these new API features.
```
pip uninstall discord.py
pip install py-cord==2.0.0b1
```

After reading various articles and Discord developer blogs, the deadline to make this migration before the loss of Bot functionality is April 2022.

## How would this feature work?
Based on the [Quick Examples](https://github.com/Pycord-Development/pycord#quick-example) section in the `PyCord` README.md and [Bot sample](https://github.com/Pycord-Development/pycord/blob/master/examples/basic_bot.py), very little of our actual codebase has to change. The code we currently have could be migrated over without difficulty.

We could even refactor some of our code (such as event scheduling) to use the new API features in `PyCord`. After making these changes, amendments to the current documentation will need to be made to reflect the use of the new library.

**Comment by Paulmski** [comment]
Interesting, I didn't realize discordpy was end of life. I agree it is important to migrate the project over to a maintained library.

It makes more sense why newer features aren't being supported in the library and we are having to manually implement HTTPS requests.

**Comment by tuanyvan** [comment]
After a short hiatus, I am now working on the migration over to Pycord in my [personal fork](https://github.com/tuanyvan/Discord-Bot/tree/feature-72-pycord). The implementation of slash commands, as of now, only requires changes to function decorators and function structure.

It also requires a large revamp to documentation that I will take care of at each step (changes to application scope, removal of `discord` dependency before the installation of `py-cord`, etc.).

Within this week, I plan to push the changes to its own branch (feature-72-pycord) once I get a good minimum viable product of equivalent functionality to the `main` build. In the future, optimizations to the code after migration (such as changing HTTP POST + Route object requests to Pycord equivalents) can become a good first issue for future contributors.

**Comment by Paulmski** [comment]
Thanks for taking on this issue it seems like it will be a quite a task. If you want any help let me know or someone to review work let me know.
